### ISSUE TITLE
Gutenberg compatibility

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Document-Feedback#14]
As of Gutenberg 2.7, Document Feedback appears to work fine within the Gutenberg editor:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/36432/38993686-27842dba-4399-11e8-8372-ea0585574123.png">

**Comment by maevelander** [comment]
Tested again at 5.0. Still works. Updating 'tested up to' tag and closing this issue.
